- sheepdog/utils/transforms/graph_to_doc.py
Fix bug introduced by mis-refactoring of the [gdcapi implementation](https://github.com/uc-cdis/gdcapi/blob/6fdde1995c45f9c977ecee0f86658166a1e81d72/gdcapi/resources/submission/transforms/gdc_graph2doc.py#L698-L700) in `ExportFile.get_tabular`.
R? @philloooo
> fix(graph to doc): fix bug in encode

- sheepdog/blueprint/routes/views/program/project.py
support `format` as the GET parameter for this endpoint https://github.com/NCI-GDC/gdcapi/blob/develop/gdcapi/resources/submission/transforms/gdc_graph2doc.py#L530
r? @rudyardrichter
> fix(export): backward compat with format

- sheepdog/transactions/upload/entity.py
- use entity.action instead of transaction.role to determine whether this user is doing a `create` or `update` on the entity
- fix indexd creation code to pass all required fields
> fix(indexd): fix index creation

- dev-requirements.txt
- requirements.txt
- sheepdog/transactions/deletion/transaction.py
- sheepdog/transactions/upload/entity.py
- tests/test_vacuous.py
Resolves #21.
If a file exists in the index service with the same size and hashes as a file being uploaded, do not create a new index record with a new UUID.
> fix(index): only register new index if none exists

- dev-requirements.txt
- requirements.txt
- sheepdog/transactions/deletion/transaction.py
- tests/test_vacuous.py
Remove `gdcapi` requirement that should not have been there and correct `gdcdatamodel` requirement.
(I blame `pipreqs` [and myself])
> fix(gdcapi-req): remove erroneous requirements

- _config.yml
- docs/_config.yml
- docs/build/html/index.html
- docs/index.html
GitHub pages setup from last PR not working correctly because the `_config.yml` goes in the folder being served from, i.e. `/docs`.
> feat(docs): fix jekyll config for GH pages

- sheepdog/blueprint/routes/__init__.py
- sheepdog/blueprint/routes/views/program/project.py
- sheepdog/utils/transforms/graph_to_doc.py
Resolves #18.
Tested with 100,000 `Case` files. Exporting the TSV takes ~170~ 167 seconds (down from 185s), with ~158~ 153 seconds cumulatively due to `psqlgraph.CommonBase.__getitem__`. ~Adjusting the `yield_per` size for the query has limited effect on the time and somewhere in the 500–1500 range seems to be optimal.~ As it turns out, `query.all()` is faster for this case.
Exporting 1,000 cases takes 1.96 seconds, with 1.69 due to `psqlgraph.CommonBase.__getitem__`.
- Exporting 100,000 `Case` nodes takes 15s locally (down from 185s), with 13s due to `sqlalchemy.orm.loading`.
- Exporting 1,000 `Case` nodes takes about 0.3s, with most of the time due to checking auth and application handling.
- This will absolutely not work on nodes with nested links, for instance if a `Case` node wanted …
> feat(export): add function to export all nodes under project

- sheepdog/transactions/upload/entity.py
transaction has a way to get phsids/dbgap_accession_numbers, so use that
instead of messing with global flask variables
> fix(global): get rid of global variable

- sheepdog/transactions/deletion/transaction.py
BUG: some nodes have no required fields defined in a dictionary and it was breaking the code
Changed code to use safe .get() method to get dictionary items
> fix(deletion): fields deletion corner case fixed

- sheepdog/transactions/deletion/transaction.py
This is a temporary patch till `gdcdictionary.schemas[node_type]['required']` has everything that is actually required for each `node_type`
> fix(deletion): Workaround for gdc dictionary broken required fields

- Dockerfile
- deployment/nginx/nginx.conf
- deployment/nginx/uwsgi.conf
- deployment/uwsgi/uwsgi.ini
- dockerrun.bash
integrate nginx logging and nginx uwsgi config
with X-Forwarded-For and X-UserId headers
supplied by the reverse proxy, so peregrine logs
have the client ip and user id
also increase uwsgi buffer-size - not happy with big headers
from jwt
http://uwsgi-docs.readthedocs.io/en/latest/Options.html#buffer-size
resolves #63
> fix(logging): log real user id and ip addr

- deployment/nginx/nginx.conf
applies step 1 in https://hexadix.com/slowloris-dos-attack-mitigation-nginx-web-server/
to mitigate slowloris to handle https://github.com/uc-cdis/cloud-automation/issues/219
@rpowellgit  told me just do step 1
> chore(nginx): up worker connection limit

- sheepdog/transactions/deletion/entity.py
if the data file hasn't been touched after the node is uploaded(if it's touched with any data upload endpoint, it will be moved to various states), the file_state is in None state, it should allow deletion.
> fix(delete): allow deletion if state is not set

- sheepdog/globals.py
- sheepdog/transactions/upload/sub_entities.py
- sheepdog/utils/__init__.py
- tests/integration/submission/test_upload.py
This PR addresses the following:
* `sheepdog.utils.get_indexd_state` checks the state of a primary url type defined in `sheepdog.globals.PRIMARY_URL_TYPE`
* Add `sheepdog.globals.RELEASED_NODE_STATES` to cover possible node states that are treated as "released"
* Update unit tests to cover different "released" states.
> [fix][API-533]: fix sheepdog.utils.get_indexd_state and released node states

- sheepdog/api.py
Sheepdog continues executing when a new dictionary fails to deploy.
We would prefer if it bombed out, so we get an obvious failure rather than debug unexpected behavior later.  For example - the following error was only revealed when the ETL process failed, and Thanh manually determined that a database table was not in sync with the dictionary, then re-roll everything to see if the migration hadn't run, and finally checked sheepdog logs:
```
ERROR:sheepdog.api:Fail to migrate database, continuing anyway
Traceback (most recent call last)
File "/sheepdog/sheepdog/api.py", line 86, in migrate_database
postgres_admin.create_graph_tables(app.db, timeout=1)
File "/sheepdog/src/datamodelutils/datamodelutils/postgres_admin.py", line 195, in create_graph_tables
...
IdentifierError: Identifier …
```
> PXD-1961 fix(db_migrate): exit the program when sheepdog fail to migrate the db

- sheepdog/transactions/upload/sub_entities.py
- sheepdog/transactions/upload/transaction.py
See following error:
Traceback (most recent call last):
{{ File "/sheepdog/sheepdog/transactions/upload/_init_.py", line 38, in single_transaction_worker}}
{{ transaction.parse_doc(*doc_args)}}
{{ File "/sheepdog/sheepdog/transactions/upload/transaction.py", line 81, in parse_doc}}
{{ self.parse_entities(data)}}
{{ File "/sheepdog/sheepdog/transactions/upload/transaction.py", line 112, in parse_entities}}
{{ self.instantiate()}}
{{ File "/sheepdog/sheepdog/transactions/upload/transaction.py", line 163, in instantiate}}
{{ entity.instantiate()}}
{{ File "/sheepdog/sheepdog/transactions/upload/entity.py", line 149, in instantiate}}
{{ self.node = self.get_node_merge()}}
{{ File "/sheepdog/sheepdog/transactions/upload/sub_entities.py", line 180, in get_node_merge}}
{{ node = …
> PXD-1960 fix(message): fix error message

- sheepdog/utils/__init__.py
- tests/unit/submission/test_utils.py
- Change validation function to not get node from indexd, because it's
already gotten in this context
- Add check for node.batch_id for submitted files
- Add check for indexd.doc version and release number for released files
> fix(api-560): Add extra checks for upload/delete

- sheepdog/utils/transforms/__init__.py
the data coming in is already with proper encoding (ascii/utf-8), just use the encoded string to pass to transformation
- csv library doesn't work with unicode, pass the original utf-8 encoded string instead
> fix(unicode): don't cast to unicode for tsv

- dev-requirements.txt
- sheepdog/utils/transforms/graph_to_doc.py
- tests/unit/test_templates.py
- Adds 'urls' field to template TSVs and JSONs 
- Changes export logic to not check this new 'urls' field (because it's not in the dictionary)
- Unit tests for above 
(From Jira description:) 
To properly register data_files in Windmill, uses need to submit the metadata property 'urls' with the value of their s3 bucket location of the submitted file, for example:
"urls":"s3://data-bucket/folder1/file1.csv"
However, there is no "urls" in any of the data_file template tsvs, it is not in the form submission for data files, and it is not listed as a property in the data dictionary viewer, which results in a large amount of support intervention and user training.
- (incidental/unrelated to this issue) changes dev-requirements.txt to require pytest==3.6.3 because 4.0.1 breaks the tests
> [PXD-2275] Make required data_file field 'urls' visible to users in template TSVs and JSONs

- sheepdog/transactions/upload/sub_entities.py
Fix the ACL update of blank records
- When linking metadata to an existing indexd record, set the ACL to the project the metadata is uploaded into
> fix(update-acl): use project code

- requirements.txt
- dictionaryutils 2.0.0 -> 2.0.4 to support nested subgroups
- gdcdatamodel 1.3.4 -> 1.3.6 to support nested subgroups
> chore(dictutils): bump dictutils

- sheepdog/utils/transforms/graph_to_doc.py
Fix bug in Sheepdog's `export all` endpoint (`export/?node_label=xxx`), which tried to export the `urls` of a data node
- remove the urls from the exported fields
> fix(urls-export)

- dev-requirements.txt
- requirements.txt
- sheepdog/globals.py
- sheepdog/test_settings.py
- sheepdog/transactions/upload/entity.py
- sheepdog/transactions/upload/sub_entities.py
- sheepdog/transactions/upload/transaction.py
- tests/integration/conftest.py
- tests/integration/submission/test_upload.py
- tests/integration/submission/test_versioning.py
- tests/integration/submission/utils.py
Adds an extra check to restrict versioning released nodes that does not include a change in either md5 or file_size
> feat(upload): Restrict versioning nodes without changes in file_size or md5

- sheepdog/transactions/upload/sub_entities.py
When an uploaded file is mapped, set the ACL to `[program, project.dbgap_accession_number]` instead of `[program, project.code]`
- Fixes a bug where a user could not download a file they have access to
> fix(data-upload-acl)

- docs/api_reference/substitutions.rst
- openapi/swagger.yml
- sheepdog/blueprint/routes/views/program/project.py
Fixes PXD-2092.
* Fixed Swagger docs of export
* Also renamed `program_id` and `project_id` to `program` and `project` in Swagger docs of widely-used parameters `program` and `project` in URL path.
> PXD-2092 Fix Swagger docs of export

- sheepdog/globals.py
- sheepdog/transactions/upload/sub_entities.py
- tests/integration/conftest.py
- tests/integration/submission/test_upload.py
- tests/integration/submission/test_versioning.py
- tests/integration/submission/utils.py
Adds support for silently updating released file metadata without creating a new version
> fix(upload): handle validated file state for released files

- requirements.txt
- sheepdog/api.py
- sheepdog/transactions/transaction_base.py
- sheepdog/transactions/upload/transaction.py
Fixes a 500 error when trying to create multiple entries with the same submitter id in the same transaction (correctly returns 400).
DEPENDS ON:
- Make entity ID a separate and non-unique column on transaction snapshots.
- Change the ID column to be a real internal primary key.
> fix/snapshots: fix 500 error

- bin/setup_transactionlogs.py
Removes the drop_all in the transaction log setup. This was wiping the transaction logs for the docker-compose version of Gen3.
> fix(tl): Remove drop all

- sheepdog/transactions/transaction_base.py
The submitter will always appear correctly in transaction logs, whether or not the transaction errored.
> fix/empty-submitter: submitter in errored tx logs

- requirements.txt
Recent release from the python package `more-itertools` introduces an error on setup. Pin the old version.
> fix(more-itertools): pin version

- run.py
There was an import of `models` before the initialization of configured dictionary when run locally, which made the initialization of models not honor the actual dictionary. This patch fixes this issue.
* Fix the bug loading the wrong dictionary when running locally with `run.py`
> chore(load-dict-local): fix loading dict locally

- sheepdog/transactions/upload/entity.py
- tests/integration/submission/test_upload.py
Adds check if uploaded document has `new_submitter_id` and set as the submitter_id
> feat(upload): set submitter_id with new_submiter_id

- README.md
- deployment/uwsgi/uwsgi.ini
Don't use lazy application initialization setting in uwsgi, which was causing multiple workers to try to open the database simultaneously (and fail if they couldn't).
> fix(deadlock): un-lazy uwsgi

- dev-requirements.txt
- requirements.txt
- sheepdog/blueprint/routes/views/program/__init__.py
- sheepdog/utils/transforms/bcr_xml_to_json.py
Use PyYaml safe_load() instead of load()
Upgrade PyYaml to 5.1
> [PXP-2658] Upgrade PyYAML to 5.1 and use safe_load()

- sheepdog/transactions/upload/entity.py
- sheepdog/transactions/upload/entity_factory.py
- sheepdog/utils/transforms/__init__.py
- tests/integration/datadict/submission/test_endpoints.py
- tests/integration/datadict/submission/test_upload.py
Fix "unable to parse entity" errors when submitting a JSON or TSV (templates use asterisks for required properties)
- fix the parsing of asterisks in properties for TSV and JSON metadata submission
- add tests for TSV and CSV submission
- add tests for TSV and JSON submission with asterisks
> PXP-2401 Fix/asterisk

- build_openapi.py
- openapi/docstring_parser.py
- openapi/swagger.yml
- sheepdog/blueprint/routes/views/program/project.py
Add `Content-Type` header info to the swagger doc
- Swagger documentation describes accepted `Content-Type` for entity submission
> doc(headers): handle headers in swagger doc

- deployment/uwsgi/uwsgi.ini
- sheepdog/blueprint/routes/views/program/project.py
- tests/conftest.py
Actually, there were two issues:
* `harakiri` defined in `uwsgi.ini` is a global timeout, it will kill the worker process regardless of `set_user_harakiri`.
* Streaming responses without `stream_with_context()` will call `teardown_request()` hooks (where we cleared user HARAKIRI) immediately after returning the `flask.Response` instance, not after finishing streaming everything as expected.
Upstream bug in testing framework is fixed in pallets/flask#3157.
* Timeout is disabled for export endpoint
> PXD-2948: disable timeout for export

- requirements.txt
- sheepdog/errors.py
- sheepdog/transactions/upload/__init__.py
- sheepdog/transactions/upload/transaction.py
- tests/integration/datadict/submission/test_endpoints.py
- tests/integration/datadictwithobjid/submission/test_upload.py
- tests/integration/datadictwithobjid/submission/utils.py
Auto migration is in uc-cdis/datamodelutils#6.
uc-cdis/gdcdatamodel#12 replaced indexes on these columns with unique ones:
* `program.name`
* `project.code`
also added unique indexes for:
* `(project_id, submitter_id)` of other nodes
* added unique indexes for uniqueKeys
* Sheepdog will now create (or replace) the missing indexes during migration
* New unique indexes have been added to all nodes uc-cdis/gdcdatamodel#12
> PXD-2916: implement uniqueKeys

- requirements.txt
bump gdcdictionary because error `The 'gdcdictionary~=1.1' distribution was not found and is required by datamodelutils` is thrown when using `datamodelutils` during sheepdog setup
goes with https://github.com/uc-cdis/datamodelutils/pull/9
- datamodelutils latest version
> chore(gdcdictionary)

- .travis.yml
testing this out 
Instead of `if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then *test the things*; fi` just tell Travis to allow 3.6 failure. Then there are no false positives
> add allow_failures in .travis.yml

- .travis.yml
- dev-requirements.txt
- tests/conftest.py
- tests/integration/datadict/conftest.py
- tests/utils.py
Remove cirrus, fence, and userdatamodel from dev-requirements.txt; just inline the code for token generation (= copy paste a bunch of code from fence/fence/jwt/token to sheepdog/tests/utils, but at least fence is no longer a dependency) 
- Remove cirrus from dev-requirements
- Remove fence from dev-requirements
- Remove userdatamodel from dev-requirements
> [PXP-3221] Remove fence dependency

- sheepdog/transactions/upload/sub_entities.py
`IndexClient` is using `urljoin(base_url, '/'.join(parts))`.
- Fixed a bug in Indexd API calling when base_url has subpath
> Fix issue using abs path

- dev-requirements.txt
- requirements.txt
The point was to bump sqlalchemy; all these other bumps are to fix the issues that arose from the sqlalchemy bump
bump sqlalchemy from 0.9.9 to 1.3.5
bump dictionaryutils from 2.0.4 to 2.0.7
bump psqlgraph to 2.0.2
bump gen3datamodel to 2.0.2
bump indexd from 1.0.8 to 1.1.2
bump authutils to 3.1.1
bump requests to 2.22.0
add rbac-client
bump datamodelutils to 0.4.7
> bump sqlalchemy from 0.9.9 to 1.3.3

- requirements.txt
- bump gdcdictionary to gen3dictionary 2.0.0
> bump gdcdictionary to gen3dictionary

- requirements.txt
- sheepdog/transactions/upload/sub_entities.py
Update authz field in blank indexd record in data upload flow
Sync new revision from indexd server after _update_acl_uploader_for_file
temporarily pin rx==1.6.1 until sheepdog is python 3
> fix(data-upload-authz): update authz field and fix revision

- dev-requirements.txt
- requirements.txt
- run.py
Patch `run.py` so that gen3authz requests are mocked when we run sheepdog locally
> fix(run.py): mock arborist calls

- dev-requirements.txt
- requirements.txt
- sheepdog/blueprint/routes/views/program/project.py
- tests/conftest.py
- tests/integration/datadict/conftest.py
- tests/integration/datadict/submission/test_endpoints.py
- tests/integration/datadictwithobjid/conftest.py
- tests/integration/datadictwithobjid/submission/test_endpoints.py
- tests/integration/datadictwithobjid/submission/test_upload.py
Bump flask to the latest version
also bump pytest to 4.6.5 (latest version that supports python 2) and pytest-flask to 0.15.0 (latest version)
- Flask 1.1.1, Werkzeug 0.16.0
> chore(flask): flask 1.1.1

- sheepdog/auth/__init__.py
When `AUTH_SUBMISSION_LIST` config is True (which is the default value), sheepdog makes calls to function `validate_request`. This function used to be imported but this piece of code was removed by mistake in #298 
- Fix `validate_request` bug when `AUTH_SUBMISSION_LIST` config is not set or set to True
> fix(AUTH_SUBMISSION_LIST): import authutils validate_request

- sheepdog/transactions/transaction_base.py
- sheepdog/transactions/upload/transaction.py
- sheepdog/utils/transforms/graph_to_doc.py
Return a descriptive message instead of just "Unable to parse entity, Nothing to submit"
- When trying to submit a metadata record to a node that's not in the dictionary, user will receive an explanatory error message
> chore(error-handling): catch error and add details for user

- .travis.yml
- dev-requirements.txt
- requirements.txt
- sheepdog/transactions/upload/sub_entities.py
PXP-4710: https://ctds-planx.atlassian.net/browse/PXP-4710
Update Sheepdog to use new Indexd aliases endpoint rather than deprecated aliases endpoint (https://github.com/uc-cdis/indexd/pull/248)
Background: It's not documented why, but sheepdog creates an indexd alias in the format {program-id}/{submitter-id} for every data file uploaded.
This PR also bumps versions of `indexd` and `indexclient`, and fixes some dependency issues (update `lxml` to py3 compatible version)
- Update Sheepdog to use new Indexd aliases endpoint rather than deprecated aliases endpoint (https://github.com/uc-cdis/indexd/pull/248)
- Update `lxml` from 3.8.0 -> 4.4.0 (versions <4.0.0 are not compatible with python3)
- Update `indexclient` version to 2.0.0
- Update `indexd` version to 2.3.0 in dev-requirements.txt
- …
> (PXP-4710) Fix/update indexd aliases

- dev-requirements.txt
- sheepdog/auth/__init__.py
- sheepdog/blueprint/routes/views/__init__.py
- sheepdog/blueprint/routes/views/program/__init__.py
- sheepdog/blueprint/routes/views/program/project.py
- tests/conftest.py
- tests/integration/datadict/conftest.py
- tests/integration/datadict/submission/test_admin_endpoints.py
- tests/integration/datadict/submission/test_endpoints.py
- tests/integration/datadict/submission/test_upload.py
- tests/integration/datadictwithobjid/conftest.py
- tests/integration/datadictwithobjid/submission/test_endpoints.py
- tests/integration/datadictwithobjid/submission/test_upload.py
- tests/utils.py
Switches Sheepdog authz handling of program/project CRUD to centralized auth/Arborist.
See https://github.com/uc-cdis/commons-users/pull/810 for new Sheepdog admin policy.
(For QAs' benefit) How to test:
- See PR linked above for example of how to toggle for a given user the old `admin: true/false` and the new admin policy 
- Verify that the API behaves according to this matrix:
```
User DOES have Sheepdog admin policy: All CRUD authorized.
Admin is FALSE:
Create program: Authorized
Delete program: Authorized
Create project: Authorized
Delete project: Authorized
Admin is TRUE:
Create program: Authorized
Delete program: Authorized
Create project: Authorized
Delete project: Authorized
User does NOT have Sheepdog admin policy: All CRUD not authorized.
(Also check that they are 403s in …
```
> PXP-4102 Feat/arb admin

- sheepdog/utils/transforms/__init__.py
- tests/integration/datadict/submission/test_endpoints.py
Fix the error that occurs when attempting to convert a float to an integer when submitting a tsv/csv file with a field with type "number". 
Fix sheepdog X.0 integer handling
> fixed float to integer conversion and added a unit test

- sheepdog/utils/transforms/graph_to_doc.py
- tests/integration/datadict/submission/data/experimental_metadata.json
- tests/integration/datadict/submission/test_endpoints.py
When exporting entities as a tsv file Null values would have 'None' instead of an empty string. This would cause an error when resubmitting. Fixed by checking file format and making Null values an empty string when the format is tsv.
> PXP-5663 Fix/exporting none issue

- requirements.txt
Setting new `authutils` due to a compatibility issue between `Sheepdog` and authlib `0.14.3`:
More details:
https://github.com/uc-cdis/authutils/pull/41
This should address the compatibility issue with authlib `0.14.3`
> fix(qa): Pin authlib 0.14.2 due to authlib issue

- sheepdog/transactions/upload/sub_entities.py
- tests/integration/datadictwithobjid/submission/test_upload.py
- Only write acl and authz fields of corresponding Indexd record during data submission iff both fields are empty to begin with. Prevents authz field from being unintentionally populated in commons not using authz.
- Note that this PR will cause Sheepdog behavior to change slightly during a data submission flow in which the acl and/or authz field are previously populated in the corresponding Indexd record and the Indexd uploader field is not null and the Sheepdog submitter does not match the Indexd uploader. While the existing behavior will cause data submission to fail and report an error message to the user, this PR’s changes will mean that data submission can still succeed in this case of populated acl/authz and uploader mismatch. I believe this change in behavior is not problematic in …
> (PXP-6580): fix data submission by only writing acl and authz iff both are empty

- sheepdog/api.py
- sheepdog/transactions/upload/entity.py
- sheepdog/transactions/upload/entity_factory.py
Jira Ticket: [PXP-7094](https://ctds-planx.atlassian.net/browse/PXP-7094)
For reasons pertaining to Explorer functionality, the MIDRC commons dictionary uses more specific `category` names for some of the data file nodes (e.g. `category: genomic_data_file` for the [virus_sequence node](https://github.com/uc-cdis/midrc_dictionary/blob/7ef97f0f1b126f4e4526840983b7553490804539/gdcdictionary/schemas/virus_sequence.yaml#L7)).
This has been causing a data upload/file mapping integration test to fail for [cdis-manifest MIDRC PRs](https://github.com/uc-cdis/cdis-manifest/pull/2267) because a `NonFileUploadEntity` instance is created instead of a `FileUploadEntity` instance that would be responsible for updating `acl`/`authz` in Indexd.
- Fix mapping files for any node category ending in `"_file"` …
> (PXP-7094): fix mapping file for any node category ending in "_file" (e.g. "genomic_data_file")

- sheepdog/transactions/upload/sub_entities.py
Fix `'HTTPError' object has no attribute 'message'`
- Fix 500 error from Sheepdog when Indexd is unavailable
> Fix 500 error when Indexd is unavailable

- requirements.txt
- sheepdog/utils/transforms/__init__.py
- sheepdog/utils/transforms/graph_to_doc.py
Jira Ticket: [PXP-8123](https://ctds-planx.atlassian.net/browse/PXP-8123)
goes with https://github.com/uc-cdis/gdcdatamodel/pull/33
- bug when submitting array items as TSV: `1,2,3` is parsed as `['1', '2', '3']` and we return `'1' is not of type 'number'`
- bug when exporting array items to TSV:
```
File "/sheepdog/sheepdog/utils/transforms/graph_to_doc.py", line 162, in list_to_comma_string
val = ",".join(val)
TypeError: sequence item 0: expected str instance, int found
```
- bug when reporting array items errors to users:
```
File "/sheepdog/sheepdog/transactions/upload/transaction.py", line 52, in record_errors
keys = [".".join(error.path)] if error.path else []
TypeError: sequence item 1: expected str instance, int found
```
- Fix bug when submitting array items as TSV
- Fix bug when …
> PXP-8123 Fix various TSV arrays bugs

- Dockerfile
Jira Ticket: [PXP-8940](https://ctds-planx.atlassian.net/browse/PXP-8940)
- Use `python3.6-buster` base Debian image with updated certs instead of base Alpine image
> PXP-8940 Use python3.6-buster base image

- .secrets.baseline
- requirements.txt
- tests/integration/datadict/schemas/dictionary.json
- tests/integration/datadict/submission/test_endpoints.py
- tests/integration/datadict/test_vacuous.py
Jira Ticket: [PXP-9192](https://ctds-planx.atlassian.net/browse/PXP-9192)
requires https://github.com/uc-cdis/gdcdatamodel/pull/35
- Validate `jsonschema` format during submission
- Sheepdog now validates formats. If your dictionary uses formats and you have existing data or submission pipelines that do not respect these formats, this might be a breaking change
- `gen3datamodel` to 3.1.0
> PXP-9192 Validate format

- .secrets.baseline
- tests/integration/datadict/conftest.py
- tests/integration/datadict/submission/test_endpoints.py
- tests/integration/datadict/test_ssl_and_isolation_level.py
- tests/integration/datadictwithobjid/conftest.py
- tests/integration/datadictwithobjid/submission/test_endpoints.py
- tests/integration/datadictwithobjid/test_ssl_and_isolation_level.py
Jira Ticket: [PXP-9266](https://ctds-planx.atlassian.net/browse/PXP-9266)
- Split "use SSL" and "isolation level" unit tests into their own file. The previous parametrization caused the tests to take 30+ min to run, because all tests that use the `pg_driver` fixture were ran 12 times
> PXP-9266 Split SSL and isolation level tests

- docs/local_dev_environment.md
- sample_usage.py
* Local Development notes and sample usage
> Add Local dev environment and sample usage

- .pre-commit-config.yaml
- sheepdog/utils/transforms/__init__.py
- Fix issue where arrays of ints gets converted to array of floats
> chore(tmp): debug lines

- poetry.lock
- pyproject.toml
Jira Ticket: [PXP-10952](https://ctds-planx.atlassian.net/browse/PXP-10952)
see https://github.com/uc-cdis/dictionaryutils/pull/85
- Fix validation issue when submitting null values allowed by a `oneOf/anyOf` dictionary property definition
[PXP-10952]: https://ctds-planx.atlassian.net/browse/PXP-10952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PXP-10952 Fix validation issue when submitting null values

- poetry.lock
- pyproject.toml
Jira Ticket: [PPS-810](https://ctds-planx.atlassian.net/browse/PPS-810)
* cryptography to 42.0.5
[PPS-810]: https://ctds-planx.atlassian.net/browse/PPS-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (PPS-810) bump cryptography to 42.0.5

- Dockerfile
- sheepdog/version_data.py
Link to JIRA ticket if there is one: [MIDRC-938](https://ctds-planx.atlassian.net/browse/MIDRC-938)
* Fixed: `version_data.py` was being updated at an incorrect location during docker image build
[MIDRC-938]: https://ctds-planx.atlassian.net/browse/MIDRC-938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Fix] Sheepdog populating version info incorrectly

- deployment/wsgi/gunicorn.conf.py
Link to JIRA ticket if there is one:  [MIDRC-946](https://ctds-planx.atlassian.net/browse/MIDRC-946)
* Add more workers to sheepdog's gunicorn server to improve responsiveness during bottlenecks
[MIDRC-946]: https://ctds-planx.atlassian.net/browse/MIDRC-946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update gunicorn config to improve sheepdog's responsiveness
