- .travis.yml
Enable Travis with coverage reporting to codacy.
> feat(coverage): add travis file

- README.md
- dev-requirements.txt
- docs/Makefile
- requirements.txt
- Add badges in README
- Move requirements for documentation generation to `dev-requirements.txt`
- More explanation in README
> fix(docs): fix docs reqs and improve readme

- sheepdog/transactions/upload/entity.py
- tests/submission/utils.py
add a metadata field to request @rudyardrichter @philloooo
> feat(metadata): add metadata to request

- sheepdog/utils/transforms/graph_to_doc.py
- tests/submission/test_endpoints.py
export for ids is broken because it's [yielding](https://github.com/uc-cdis/sheepdog/blob/master/sheepdog/utils/transforms/graph_to_doc.py#L666) a [generator](https://github.com/uc-cdis/sheepdog/blob/master/sheepdog/utils/transforms/graph_to_doc.py#L266)
- remove the nested yields
- add regression tests
> fix(export): fix json dump

- requirements.txt
- sheepdog/transactions/upload/entity.py
- sheepdog/utils/__init__.py
- tests/submission/test_endpoints.py
- tests/submission/utils.py
change from using project_id to dbgap_accession_numbers of program and project
@philloooo @rudyardrichter
> fix(dbgap): change from project_id to dbgap

- requirements.txt
This should eliminate the conflict with regard to setuptools.
> Update cdisutils pin

- sheepdog/transactions/deletion/transaction.py
- sheepdog/transactions/upload/__init__.py
- tests/submission/test_endpoints.py
- When deleting fields from entities, check if field is required
- Added test
- Brought back the forgotten field deletion test
> fix(deletion)[SV-980]: Check if field is required when removing

- requirements.txt
the uc-cdis gdcdatamodel that works for dictionary that does not have `case`
> feat(datamodel): use uc-cdis datamodel

- sheepdog/transactions/upload/entity.py
- Update config to use instance from class instead of global
> fix(config): Update config to use instance from class

- dev-requirements.txt
- requirements.txt
- tests/conftest.py
> fix(version): bump userdatamodel latest authutils

- sheepdog/dev_settings.py
switch to fence_test database for dev_testing
@rudyardrichter @Avantol13
> fix(database): user fence_test as user db

- sheepdog/transactions/upload/entity.py
fixed the `release/fox` branch
> fix(branch): [TT-311] fixed previous release branch

- requirements.txt
- sheepdog/transactions/submission/transaction.py
- sheepdog/utils/__init__.py
r @philloooo @rudyardrichter 
fix bug empty dbgap_accession_numbers
The logic is:
- if program has dbgap_access_number assign it to the aggregation number, otherwise skip
- then if the project has dbgap_access_number append it to the aggregation one. with `,`. Then strip it.
- else if project doesn't have one, don't need to do anything.
I think it is a correct logic
> fix(acl): fix bug with acl None

- sheepdog/api.py
support auto migrate. default to True if sheepdog is run as standalone app
> chore(db): support auto migrate

- sheepdog/utils/transforms/bcr_xml_to_json.py
> fix(xml): Fix calls to isinstance

- requirements.txt
- sheepdog/api.py
only migrate if schema is changed
blocked by https://github.com/uc-cdis/datamodelutils/pull/3
> chore(db): check if need migration

- sheepdog/utils/transforms/graph_to_doc.py
- Fix template code with second list to skip showing fields,
adding batch_id and state_comment
> fix(template): Fix template code

- sheepdog/blueprint/__init__.py
- complete flexibility for route overwriting
- route validity check
> feat(create_blueprint): Overwrite blueprints

- dev-requirements.txt
- requirements.txt
- sheepdog/transactions/upload/sub_entities.py
- sheepdog/utils/__init__.py
coupled with https://github.com/uc-cdis/indexd/pull/109
> feat(acl): use indexd doc.acl

- sheepdog/transactions/upload/__init__.py
- sheepdog/utils/transforms/bcr_xml_to_json.py
change the way depth is checked against
minor code cleanups
> fix(tt-578): bcr xml link inference

- Dockerfile
- bin/setup_psqlgraph.py
- bin/setup_test_database.py
- sheepdog/blueprint/routes/views/program/project.py
- sheepdog/utils/transforms/graph_to_doc.py
- tests/integration/submission/test_endpoints.py
Think this is close to what we want? 
ex:
https://reuben.planx-pla.net/api/v0/submission/DEV/test/export/?node_label=case&format=json
> chore(export-json): support export with json

- sheepdog/utils/__init__.py
- sheepdog/utils/s3.py
- tests/integration/submission/test_upload.py
Update sheepdog.utils.s3.make_s3_request method signature.
> fix(tt-696): Centralize object store key generation

- sheepdog/utils/transforms/graph_to_doc.py
This resolves the tests in sheepdog + gdcapi (pr for gdcapi coming shortly after)
> fix(api-496): remove batch_id/state_comment from templates

- sheepdog/blueprint/routes/views/program/project.py
proxy_request returns two separate data types.
https://github.com/uc-cdis/sheepdog/blob/master/sheepdog/utils/__init__.py#L444-L449
> fix(upload): dry run transaction

- sheepdog/blueprint/routes/views/program/__init__.py
- tests/integration/datadictwithobjid/submission/test_endpoints.py
Gracefully handle project creation attempt with duplicate code under another program
> PXD-1278 fix(error_code): fix error code

- sheepdog/transactions/upload/sub_entities.py
- tests/integration/datadict/submission/test_upload.py
- tests/integration/datadictwithobjid/submission/test_upload.py
Want to replace the previous url instead of appending
> PXD-1089 fix(urls): fix PUT new url appends to list

- dev-requirements.txt
- requirements.txt
- sheepdog/transactions/upload/sub_entities.py
when url provided, the default value is [] not None
> Chore/indexd - fix indexd update when url is not provided

- dev-requirements.txt
- requirements.txt
- sheepdog/api.py
- tests/integration/datadict/api.py
- tests/integration/datadictwithobjid/api.py
Fix github security issues 
flask==0.12.4
requests==2.20.0
cryptography==2.3
cdiserrors.git@0.1.1
pytest-flask==0.11.0
> PXD-1797 Fix/flask

- Jenkinsfile
> chore(Jenkinsfile): run integration tests on PRs

- dev-requirements.txt
- sheepdog/transactions/upload/entity.py
- sheepdog/utils/transforms/graph_to_doc.py
- tests/unit/test_templates.py
Add required field indicator (i.e. asterisk) to relevant fields in TSV and JSON templates. 
Add unit tests for same. 
> [PXD-342] Feat/required-indicator

- sheepdog/api.py
> fix(logget): fix logger for db migration

- dev-requirements.txt
- urllib3 1.22->1.23 for tests to address security vulnerability
> (chore(urllib3): bump urllib3 for tests

- sheepdog/transactions/upload/sub_entities.py
- ACL should contain program AND project so that users with access to the whole program have access
> fix(data-upload-acl): add program

- dev-requirements.txt
- requirements.txt
- sheepdog/globals.py
- sheepdog/transactions/deletion/entity.py
- sheepdog/transactions/deletion/transaction.py
- sheepdog/utils/__init__.py
- Implemented API-577 andn API-578
> API-577 and API-578 delete state

- sheepdog/transactions/upload/sub_entities.py
- sheepdog/utils/transforms/graph_to_doc.py
- tests/integration/datadict/submission/test_endpoints.py
Bug fixes in the export functions
- fix encoding bug in sheepdog multiple node export
- fix asterisk bug in sheepdog single node export
> PXP-2338 Fix/export encode

- Jenkinsfile.performance
> adding Jenkinsfile.performance

- Jenkinsfile.performance
Update of `cdis-jenkins-lib` branch.
> feat(perf): cdis-jenkins-lib branch

- sheepdog/globals.py
- sheepdog/transactions/deletion/entity.py
- sheepdog/transactions/deletion/transaction.py
- sheepdog/utils/__init__.py
- Revert code adding delete state to indexd, which is from
https://github.com/uc-cdis/sheepdog/commit/18eeea40c9e1e5de6704e265d9529e6cf3ed140f
> fix(sheepdog): Revert code adding delete state to indexd

- requirements.txt
- sheepdog/api.py
- sheepdog/transactions/transaction_base.py
- sheepdog/transactions/upload/transaction.py
Fixes a 500 error when trying to create multiple entries with the same submitter id in the same transaction (correctly returns 400).
- Make entity ID a separate and non-unique column on transaction snapshots.
- Change the ID column to be a real internal primary key.
> fix/snapshots: fix snapshot db schema

- Jenkinsfile.performance
Use `master` branch from `cdis-jenkins-lib`.
> feat(perf): merge is coming, use master

- deployment/nginx/uwsgi.conf
* Align uWSGI timeout of `/_status` requests
> Fix /_status HARAKIRI timeout

- requirements.txt
* Fix bug that POST submission may insert data with duplicate uniqueKeys successfully
> PXD-2468: Add uniqueness check back

- deployment/nginx/nginx.conf
> fix(nginx.conf): json logs

- requirements.txt
- tests/integration/datadict/submission/test_upload.py
This is actually fixed in uc-cdis/gdcdatamodel#16, this PR includes only the tests.
* Links are now case-insensitive
> PXD-2321: link case insensitivity

- requirements.txt
- sheepdog/transactions/transaction_base.py
See also: #217, uc-cdis/datamodelutils#10
* Added missing index to make submission faster
* datamodelutils bumped to 0.4.5
> PXD-3012: Add missing index to make submission faster

- sheepdog/transactions/upload/__init__.py
- sheepdog/transactions/upload/transaction.py
- tests/integration/datadict/submission/test_endpoints.py
- Handle integrity Error when there are two transactions submit data to DB
> PXD-3065 Feat/integrity handling

- Dockerfile
> chore(docker): use the pybase-1.0.2

- sheepdog/globals.py
- sheepdog/transactions/deletion/entity.py
- sheepdog/transactions/deletion/transaction.py
- sheepdog/transactions/entity_base.py
- sheepdog/transactions/upload/transaction.py
- tests/integration/datadict/submission/test_endpoints.py
- tests/integration/datadictwithobjid/submission/test_endpoints.py
deprecate "related cases" caching--not a problem if CASE_CACHE was False
> deprecate caching

- requirements.txt
- sheepdog/transactions/upload/sub_entities.py
- Fix bug with alias path building when we use a custom indexd base URL
- Fix authz resource path in newly created indexd records
- Bump indexclient to 1.6.2
> Fix indexd record and alias creation

- sheepdog/api.py
- sheepdog/dev_settings.py
- sheepdog/test_settings.py
- ARBORIST_URL environment variable replaces broken default ARBORIST config variable
> fix(arborist-url)

- dev-requirements.txt
- requirements.txt
- sheepdog/utils/transforms/graph_to_doc.py
- tests/integration/datadict/submission/test_endpoints.py
https://ctds-planx.atlassian.net/browse/PXP-6002
Fix export large amount of data
- Using streaming to export large amount of data
> fix(export): streaming

- .pre-commit-config.yaml
- .secrets.baseline
This repo has flask secret key in dev_settings.py, otherwise just a bunch of md5sum in the test files
> Add pre commit hooks and secret detection in repo

- .travis.yml
- Dockerfile
Unblocking the image build failures for `integration202103` version
> fix: disable rust build

- .travis.yml
- Dockerfile
unblocking the `integration202103` branch image build
> Disable Rust build

- sheepdog/blueprint/routes/views/__init__.py
- sheepdog/blueprint/routes/views/program/__init__.py
- Improve program/project creation error messages
> Improve program/project creation error messages

- Dockerfile
- Adopt new base img with dd apm
> chore(observability): Adopt new base img with dd apm

- .secrets.baseline
- sheepdog/blueprint/routes/__init__.py
- sheepdog/blueprint/routes/views/__init__.py
- sheepdog/blueprint/routes/views/program/__init__.py
- sheepdog/transactions/upload/__init__.py
- sheepdog/utils/parse.py
- tests/integration/datadict/submission/test_endpoints.py
- Add debug log when unable to parse JSON input
- Handle TSV/CSV data for program/project creation
> Handle TSV/CSV data for program/project creation + debug logs

- Dockerfile
- bin/setup_psqlgraph.py
- bin/setup_test_database.py
- bin/setup_transactionlogs.py
- deployment/scripts/postgresql/postgresql_test_init.sql
- deployment/uwsgi/uwsgi.ini
- dev-requirements.txt
- requirements.txt
- run_tests.bash
- sheepdog/api.py
- sheepdog/blueprint/routes/views/program/project.py
- sheepdog/test_settings.py
- sheepdog/utils/transforms/__init__.py
- sheepdog/utils/transforms/bcr_xml_to_json.py
- sheepdog/utils/transforms/graph_to_doc.py
- tests/integration/datadict/conftest.py
- tests/integration/datadict/submission/test_endpoints.py
- tests/integration/datadict/submission/test_upload.py
- tests/integration/datadictwithobjid/conftest.py
- tests/integration/datadictwithobjid/submission/test_endpoints.py
- tests/integration/datadictwithobjid/submission/test_upload.py
Jira Ticket: [PXP-xxxx](https://ctds-planx.atlassian.net/browse/PXP-xxxx)
> [ignore me] add psql ssl support

- Dockerfile
Jira Ticket: [PXP-8940](https://ctds-planx.atlassian.net/browse/PXP-8940)
fix to #358
> Use pybase3-2.0.0 base image

- .secrets.baseline
- sheepdog/utils/transforms/graph_to_doc.py
- tests/integration/datadict/submission/test_endpoints.py
fix bug introduced in #351
- Fix export for non-string array values introduced in versions 3.2.0 / 2021.10
> Fix export for non-string array values

- requirements.txt
- Upgrade Flask-Cors to version 3.0.9 or higher.
- Upgrade urllib3 to version 1.26.5 or higher.
> chore(deps): update dependencies

- docs/local_dev_environment.md
- sample_usage.py
community PR located here
https://github.com/uc-cdis/sheepdog/pull/350
> local dev environment and sample usage

- requirements.txt
- upgrade `cryptography` to latest version (and other necessary deps)
> fix(crypt): update cryptography and other required deps

- requirements.txt
This reverts commit b50fde4c78f51bd083a830ee16fabe7129e2bbe4.
> Revert "fix(crypt): update cryptography and other required deps (#381)"

- sheepdog/api.py
- tests/utils.py
- Log actual `grant_read_permissions_to_graph` errors
> Log 'grant_read_permissions_to_graph' error.

- Dockerfile
- poetry.lock
- sheepdog/blueprint/routes/views/__init__.py
- sheepdog/blueprint/routes/views/program/project.py
- sheepdog/utils/__init__.py
- tests/integration/datadict/test_ssl_and_isolation_level.py
- tests/integration/datadictwithobjid/test_ssl_and_isolation_level.py
Jira Ticket: [PPS-204](https://ctds-planx.atlassian.net/browse/PPS-204)
[PPS-204]: https://ctds-planx.atlassian.net/browse/PPS-204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PPS-204 Update dependencies

- bin/setup_psqlgraph.py
- pyproject.toml
- sheepdog/blueprint/routes/views/__init__.py
- sheepdog/blueprint/routes/views/program/project.py
- sheepdog/utils/__init__.py
Jira Ticket: [PPS-204](https://ctds-planx.atlassian.net/browse/PPS-204)
[PPS-204]: https://ctds-planx.atlassian.net/browse/PPS-204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PPS-204 Fix warnings

- .github/labeler.yml
- .github/workflows/labeler.yml
- .secrets.baseline
Jira Ticket: [GQE-74](https://ctds-planx.atlassian.net/browse/GQE-74)
[GQE-74]: https://ctds-planx.atlassian.net/browse/GQE-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> adding labeler to sheepdog

- README.md
Jira Ticket: [PXP-7365](https://ctds-planx.atlassian.net/browse/PXP-7365)
[PXP-7365]: https://ctds-planx.atlassian.net/browse/PXP-7365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add document on unique submitter-id

- .github/workflows/ci.yaml
- .secrets.baseline
- README.md
- Code coverage reported to coveralls through GH action.
- Replaces codacy badge with coveralls
> Readd code coverage with coveralls

- README.md
also adding a small note to have postgres installed.
Link to JIRA ticket if there is one: n/a
- add a bit more clarity regarding setup prereqs
> Update README.md - add postgres prerequisite

- sheepdog/blueprint/routes/views/__init__.py
- sheepdog/blueprint/routes/views/program/__init__.py
- sheepdog/blueprint/routes/views/program/project.py
Link to JIRA ticket if there is one:
> Rely on OIDC_ISSUER instead of USER_API

- pyproject.toml
* Update `pyproject.toml` to match with the new release version
> Update `pyproject.toml` to match with the new release version
